# Generated by Django 4.2.23 on 2025-08-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, default='', help_text='Enter author name', max_length=200)),
                ('title', models.CharField(help_text='Enter book title', max_length=200, unique=True)),
                ('seria', models.CharField(blank=True, default='', help_text='Enter book seria', max_length=200)),
                ('pages_count', models.PositiveSmallIntegerField(blank=True, help_text='Enter book pages count', null=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, help_text='Enter book year', null=True)),
                ('language', models.CharField(blank=True, default='', help_text='Enter number of the pages in book', max_length=200)),
                ('isbn', models.CharField(help_text='Enter book ISBN', max_length=13, unique=True)),
            ],
            options={
                'verbose_name': 'Catalog book',
                'verbose_name_plural': 'Catalog books',
                'ordering': ['title'],
            },
        ),
    ]
