# Generated by Django 4.2.23 on 2025-08-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogBook',
            fields=[
                ('author', models.CharField(blank=True, default='N/A', max_length=200)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('seria', models.CharField(blank=True, default='N/A', max_length=200)),
                ('pages_count', models.PositiveSmallIntegerField(blank=True, default='N/A')),
                ('year', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('language', models.CharField(blank=True, default='N/A', max_length=200)),
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Catalog book',
                'verbose_name_plural': 'Catalog books',
                'ordering': ['title'],
            },
        ),
    ]
