# Generated by Django 4.2.23 on 2025-08-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogbook',
            name='title',
            field=models.CharField(help_text='Enter book title', max_length=200),
        ),
    ]
