# Generated by Django 4.2.23 on 2025-08-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogbook',
            name='author',
            field=models.CharField(blank=True, default='N/A', help_text='Enter author name', max_length=200),
        ),
        migrations.AlterField(
            model_name='catalogbook',
            name='isbn',
            field=models.CharField(help_text='Enter book ISBN', max_length=13, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='catalogbook',
            name='language',
            field=models.CharField(blank=True, default='N/A', help_text='Enter number of the pages in book', max_length=200),
        ),
        migrations.AlterField(
            model_name='catalogbook',
            name='pages_count',
            field=models.PositiveSmallIntegerField(blank=True, default='N/A', help_text='Enter book pages count'),
        ),
        migrations.AlterField(
            model_name='catalogbook',
            name='seria',
            field=models.CharField(blank=True, default='N/A', help_text='Enter book seria', max_length=200),
        ),
        migrations.AlterField(
            model_name='catalogbook',
            name='title',
            field=models.CharField(help_text='Enter book title', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='catalogbook',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Enter book year', null=True),
        ),
    ]
